windows:
  hosts:
    default:
      ansible_host: 127.0.0.1
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_winrm_scheme: http
      ansible_shell_type: powershell
      ansible_user: teamcity
      ansible_password: teamcity
